// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by ModAssemblyInfo.csproj.
// Make any needed changes in ModAssemblyInfo.csproj.

namespace DisableAccidents
{
    /// <summary>
    /// Make assembly info available as constant strings.
    /// </summary>
    public class ModAssemblyInfo
    {
        public const string Name        = "DisableAccidents";
        public const string Version     = "1.0.0";
        public const string Title       = "Disable Accidents";
        public const string Description = "A simple mod to disable traffic accidents";
    }
}
